version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  express-poc:
    image: "${IMAGE_NAME}"
    restart: always
    ports:
    - "80:3000"
    environment:
      DB_HOST: mongodb://root:example@mongo:27017/
      DB_NAME: mydb
    depends_on: 
    - mongo

networks:
  exporess-poc:

